version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_individual
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tus_password
      MYSQL_DATABASE: proyecto_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306" 

  web:
    build: .
    container_name: python_app_individual
    # Añadimos esta línea para asegurar que los cambios en Python se vean al instante
    command: python -u app.py
    volumes:
      - .:/app
    ports:
      - "5002:5000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui_individual
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: tus_password
    depends_on:
      - db